import { Character, Opponent } from '../types';

export const TEST_MODE = true;

export const PREMIUM_CHARACTER_IDS = [
  'neon_reaper',
  'inferno_titan',
  'eternal_emperor'
] as const;

export function isPremiumCharacter(characterId: string): boolean {
  return (PREMIUM_CHARACTER_IDS as readonly string[]).includes(characterId);
}

export const INITIAL_CHARACTERS: Character[] = [
  {
    id: 'rookie',
    name: 'Rookie Boxer',
    description: 'Klasik boks ustası.',
    baseHealth: 100,
    basePower: 11,
    baseSpeed: 4.5,
    baseKickDamage: 12,
    baseSpecialDamage: 25,
    guardReduction: 0.50,
    punchRange: 75,
    kickRange: 105,
    cooldownReduction: 0,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'emerald',
    accentColor: '#10b981',
    avatar: 'bg-emerald-500'
  },
  {
    id: 'fast_kid',
    name: 'Fast Kick Kid',
    description: 'Son sürat tekmeler.',
    baseHealth: 80,
    basePower: 8,
    baseSpeed: 6.2,
    baseKickDamage: 18,
    baseSpecialDamage: 20,
    guardReduction: 0.40,
    punchRange: 70,
    kickRange: 125,
    cooldownReduction: 0.12,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'amber',
    accentColor: '#f59e0b',
    avatar: 'bg-amber-500'
  },
  {
    id: 'iron_fist',
    name: 'Iron Fist',
    description: 'Tek yumruk yeter.',
    baseHealth: 110,
    basePower: 18,
    baseSpeed: 3.8,
    baseKickDamage: 8,
    baseSpecialDamage: 28,
    guardReduction: 0.50,
    punchRange: 80,
    kickRange: 95,
    cooldownReduction: -0.05,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'yellow',
    accentColor: '#fbbf24',
    avatar: 'bg-yellow-500'
  },
  {
    id: 'tank_boxer',
    name: 'Tank Brawler',
    description: 'Yıkılmaz çelik duvar.',
    baseHealth: 150,
    basePower: 12,
    baseSpeed: 2.8,
    baseKickDamage: 11,
    baseSpecialDamage: 24,
    guardReduction: 0.70,
    punchRange: 75,
    kickRange: 100,
    cooldownReduction: -0.10,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'indigo',
    accentColor: '#6366f1',
    avatar: 'bg-indigo-500'
  },
  {
    id: 'shadow_fighter',
    name: 'Shadow Fighter',
    description: 'Gölgelerin efendisi.',
    baseHealth: 90,
    basePower: 10,
    baseSpeed: 5.2,
    baseKickDamage: 12,
    baseSpecialDamage: 26,
    guardReduction: 0.45,
    punchRange: 75,
    kickRange: 110,
    cooldownReduction: 0.25,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'purple',
    accentColor: '#a855f7',
    avatar: 'bg-purple-500'
  },
  {
    id: 'muay_thai',
    name: 'Muay Thai King',
    description: 'Dirsek ve diz ustası.',
    baseHealth: 105,
    basePower: 12,
    baseSpeed: 4.8,
    baseKickDamage: 16,
    baseSpecialDamage: 26,
    guardReduction: 0.45,
    punchRange: 75,
    kickRange: 120,
    cooldownReduction: 0.05,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'rose',
    accentColor: '#f43f5e',
    avatar: 'bg-rose-500'
  },
  {
    id: 'street_ninja',
    name: 'Street Ninja',
    description: 'Sessiz ama ölümcül.',
    baseHealth: 85,
    basePower: 9,
    baseSpeed: 5.8,
    baseKickDamage: 14,
    baseSpecialDamage: 24,
    guardReduction: 0.40,
    punchRange: 70,
    kickRange: 115,
    cooldownReduction: 0.15,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'green',
    accentColor: '#22c55e',
    avatar: 'bg-green-600'
  },
  {
    id: 'crazy_clown',
    name: 'Crazy Clown',
    description: 'Kaosun yaşayan hali.',
    baseHealth: 95,
    basePower: 13,
    baseSpeed: 5.0,
    baseKickDamage: 13,
    baseSpecialDamage: 27,
    guardReduction: 0.45,
    punchRange: 80,
    kickRange: 110,
    cooldownReduction: 0.10,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'fuchsia',
    accentColor: '#d946ef',
    avatar: 'bg-fuchsia-500'
  },
  {
    id: 'dragon_warrior',
    name: 'Dragon Warrior',
    description: 'Ejderha uyanıyor.',
    baseHealth: 115,
    basePower: 15,
    baseSpeed: 4.6,
    baseKickDamage: 15,
    baseSpecialDamage: 29,
    guardReduction: 0.55,
    punchRange: 80,
    kickRange: 115,
    cooldownReduction: 0.05,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'orange',
    accentColor: '#ea580c',
    avatar: 'bg-orange-600'
  },
  {
    id: 'cyber_puncher',
    name: 'Cyber Puncher',
    description: 'Hedef kilitlendi.',
    baseHealth: 110,
    basePower: 16,
    baseSpeed: 4.2,
    baseKickDamage: 12,
    baseSpecialDamage: 28,
    guardReduction: 0.60,
    punchRange: 85,
    kickRange: 105,
    cooldownReduction: 0.08,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'cyan',
    accentColor: '#06b6d4',
    avatar: 'bg-cyan-500'
  },
  {
    id: 'samurai',
    name: 'Samurai Fighter',
    description: 'Onurlu savaşçı.',
    baseHealth: 100,
    basePower: 14,
    baseSpeed: 4.5,
    baseKickDamage: 13,
    baseSpecialDamage: 28,
    guardReduction: 0.50,
    punchRange: 85,
    kickRange: 110,
    cooldownReduction: 0.05,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'red',
    accentColor: '#ef4444',
    avatar: 'bg-red-600'
  },
  {
    id: 'wrestler',
    name: 'Wrestler Beast',
    description: 'Saf kas gücü.',
    baseHealth: 140,
    basePower: 15,
    baseSpeed: 3.2,
    baseKickDamage: 11,
    baseSpecialDamage: 30,
    guardReduction: 0.65,
    punchRange: 75,
    kickRange: 100,
    cooldownReduction: -0.05,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'blue',
    accentColor: '#2563eb',
    avatar: 'bg-blue-600'
  },
  {
    id: 'kung_fu',
    name: 'Kung Fu Master',
    description: 'Dengenin büyük ustası.',
    baseHealth: 100,
    basePower: 12,
    baseSpeed: 5.0,
    baseKickDamage: 15,
    baseSpecialDamage: 26,
    guardReduction: 0.50,
    punchRange: 75,
    kickRange: 115,
    cooldownReduction: 0.15,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'amber',
    accentColor: '#d97706',
    avatar: 'bg-amber-600'
  },
  {
    id: 'boxing_queen',
    name: 'Boxing Queen',
    description: 'Ringlerin kraliçesi.',
    baseHealth: 150,
    basePower: 11,
    baseSpeed: 5.5,
    baseKickDamage: 13,
    baseSpecialDamage: 24,
    guardReduction: 0.45,
    punchRange: 75,
    kickRange: 110,
    cooldownReduction: 0.20,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: true,
    color: 'pink',
    accentColor: '#ec4899',
    avatar: 'bg-pink-500'
  },
  {
    id: 'final_boss',
    name: 'Final Boss',
    description: 'Son meydan okuma.',
    baseHealth: 160,
    basePower: 20,
    baseSpeed: 4.8,
    baseKickDamage: 18,
    baseSpecialDamage: 35,
    guardReduction: 0.65,
    punchRange: 85,
    kickRange: 120,
    cooldownReduction: 0.10,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: false,
    color: '',
    accentColor: '',
    avatar: ''
  },
  {
    id: 'neon_reaper',
    name: 'Neon Azrail',
    description: 'Neon şehrin sessiz celladı.',
    baseHealth: 115,
    basePower: 15,
    baseSpeed: 6.0,
    baseKickDamage: 19,
    baseSpecialDamage: 36,
    guardReduction: 0.45,
    punchRange: 82,
    kickRange: 120,
    cooldownReduction: 0.18,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: false,
    color: 'cyan',
    accentColor: '#22d3ee',
    avatar: 'bg-cyan-500'
  },
  {
    id: 'inferno_titan',
    name: 'Cehennem Titanı',
    description: 'Alevlerle güçlenen ağır savaşçı.',
    baseHealth: 175,
    basePower: 20,
    baseSpeed: 3.1,
    baseKickDamage: 18,
    baseSpecialDamage: 44,
    guardReduction: 0.68,
    punchRange: 86,
    kickRange: 108,
    cooldownReduction: -0.05,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: false,
    color: 'orange',
    accentColor: '#f97316',
    avatar: 'bg-orange-600'
  },
  {
    id: 'eternal_emperor',
    name: 'Ebedi İmparator',
    description: 'Kolezyumun yenilmez hükümdarı.',
    baseHealth: 160,
    basePower: 22,
    baseSpeed: 4.8,
    baseKickDamage: 23,
    baseSpecialDamage: 50,
    guardReduction: 0.62,
    punchRange: 90,
    kickRange: 120,
    cooldownReduction: 0.10,
    healthLevel: 1,
    damageLevel: 1,
    heavyDamageLevel: 1,
    speedLevel: 1,
    cooldownLevel: 1,
    unlocked: false,
    color: 'purple',
    accentColor: '#a855f7',
    avatar: 'bg-purple-600'
  }
];

export const OPPONENTS: Opponent[] = [
  {
    id: 1,
    name: 'Street Rookie',
    health: 300,
    damage: 8,
    speed: 3.0,
    color: 'emerald',
    accentColor: '#10b981',
    avatar: '🥊',
    characterId: 'street_rookie'
  },
  {
    id: 2,
    name: 'Kick King',
    health: 290,
    damage: 10,
    speed: 3.5,
    color: 'amber',
    accentColor: '#f59e0b',
    avatar: '👊',
    characterId: 'fast_kid'
  },
  {
    id: 3,
    name: 'Shaolin Iron Monk',
    health: 500,
    damage: 13,
    speed: 2.8,
    color: 'yellow',
    accentColor: '#fbbf24',
    avatar: '🧘',
    characterId: 'monk'
  },
  {
    id: 4,
    name: 'Brawler Titan',
    health: 420,
    damage: 12,
    speed: 2.5,
    color: 'indigo',
    accentColor: '#6366f1',
    avatar: '💪',
    characterId: 'tank_boxer'
  },
  {
    id: 5,
    name: 'Nightshade Shadow',
    health: 300,
    damage: 15,
    speed: 4.2,
    color: 'purple',
    accentColor: '#a855f7',
    avatar: '🕶️',
    characterId: 'shadow_fighter'
  },
  {
    id: 6,
    name: 'Siam Cyclone',
    health: 380,
    damage: 16,
    speed: 3.8,
    color: 'rose',
    accentColor: '#f43f5e',
    avatar: '🌀',
    characterId: 'muay_thai'
  },
  {
    id: 7,
    name: 'Saber Shinobi',
    health: 370,
    damage: 15,
    speed: 4.5,
    color: 'green',
    accentColor: '#22c55e',
    avatar: '🥷',
    characterId: 'street_ninja'
  },
  {
    id: 8,
    name: 'Crazy Dan Jester',
    health: 600,
    damage: 17,
    speed: 4.0,
    color: 'fuchsia',
    accentColor: '#d946ef',
    avatar: '🤡',
    characterId: 'crazy_clown'
  },
  {
    id: 9,
    name: 'Aurelius Dragon',
    health: 385,
    damage: 18,
    speed: 3.6,
    color: 'orange',
    accentColor: '#ea580c',
    avatar: '🐉',
    characterId: 'dragon_warrior'
  },
  {
    id: 10,
    name: 'Cyber X Crusher',
    health: 390,
    damage: 19,
    speed: 3.4,
    color: 'cyan',
    accentColor: '#06b6d4',
    avatar: '🤖',
    characterId: 'cyber_puncher'
  },
  {
    id: 11,
    name: 'Samurai Katashi',
    health: 455,
    damage: 20,
    speed: 3.8,
    color: 'red',
    accentColor: '#ef4444',
    avatar: '⚔️',
    characterId: 'samurai'
  },
  {
    id: 12,
    name: 'Bison El Macho',
    health: 490,
    damage: 18,
    speed: 2.8,
    color: 'blue',
    accentColor: '#2563eb',
    avatar: '🐂',
    characterId: 'wrestler'
  },
  {
    id: 13,
    name: 'Grandmaster Lee',
    health: 495,
    damage: 19,
    speed: 4.2,
    color: 'amber',
    accentColor: '#d97706',
    avatar: '🥋',
    characterId: 'kung_fu'
  },
  {
    id: 14,
    name: 'Golden Boxing Queen',
    health: 550,
    damage: 18,
    speed: 4.8,
    color: 'pink',
    accentColor: '#ec4899',
    avatar: '👑',
    characterId: 'boxing_queen'
  },
  {
    id: 15,
    name: 'Nihil Dark Lord',
    health: 600,
    damage: 24,
    speed: 4.5,
    color: 'stone',
    accentColor: '#44403c',
    avatar: '🕷️',
    characterId: 'final_boss'
  }
];

export const CHARACTER_UNLOCK_WIN_THRESHOLDS: Record<string, number> = {
  fast_kid: 3,
  iron_fist: 5,
  tank_boxer: 8,
  shadow_fighter: 11,
  muay_thai: 14,
  street_ninja: 17,
  crazy_clown: 20,
  dragon_warrior: 24,
  cyber_puncher: 28,
  samurai: 32,
  wrestler: 36,
  kung_fu: 40,
  boxing_queen: 44,
  final_boss: 48
};

// Stats calculation based on level upgrades
export function getModifiedStats(char: Character) {
 const health = (char.baseHealth * 3) + (char.healthLevel - 1) * 45;
  const punchDamage = char.basePower + (char.damageLevel - 1) * 2;
  const heavyPunchDamage = Math.floor((char.basePower * 1.8) + (char.heavyDamageLevel - 1) * 4);
  const kickDamage = (char.baseKickDamage || Math.floor(char.basePower * 1.1)) + (char.damageLevel - 1) * 3;
  const specialDamage = (char.baseSpecialDamage || Math.floor(char.basePower * 2.5)) + (char.heavyDamageLevel - 1) * 5;
  const speed = char.baseSpeed + (char.speedLevel - 1) * 0.4;
  
  // Cooldown in seconds (including base cooldown reduction)
  const cdReduction = (char.cooldownReduction || 0) + (char.cooldownLevel - 1) * 0.04;
  const punchCooldown = Math.max(0.2, 0.5 * (1 - cdReduction));
  const heavyCooldown = Math.max(0.8, 1.8 * (1 - cdReduction));
  const kickCooldown = Math.max(0.3, 0.8 * (1 - cdReduction));
  const throwCooldown = Math.max(2.0, 4.5 * (1 - cdReduction));

  return {
    health,
    punchDamage,
    heavyPunchDamage,
    kickDamage,
    specialDamage,
    throwDamage: specialDamage, // mapped to throwDamage for compatibility
    speed,
    punchRange: char.punchRange || 75,
    kickRange: char.kickRange || 105,
    guardReduction: char.guardReduction || 0.50,
    punchCooldown,
    heavyCooldown,
    kickCooldown,
    throwCooldown
  };
}


